databases:
  - name: newlifehospital
    databaseName: newlifehospital
    user: newlifehospital_user

services:
  - type: web
    name: newlife
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: newlifehospital
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false